"""
Django settings for sistema_logueo project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent #Sirve para indicar nuestros directorios 


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/


#El SECRET_KEY se encarga principalmente de la encriptacion de los datos 
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1#kbyv2zvku+gsne_crw386uc-2ibasjr=ltfb-rpi#7@at1*g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  #Esta propiedad nos permite decirle a la aplicacion si estamos en modo trabajo o no
#Si lo ponemos en false la app ya no estara dando informacion a otras fuentes 


ALLOWED_HOSTS = [] #Esta propiedad lo que hace es cuales direcciones tienen  permitido entrar a nuestro servidor


# Application definition


#Django nos permite dividir el proyecto en diversas aplicaciones 
#Aqui lo añadimos de forma procedural
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]



#Esto es para decirle a python como queremos que corra nuestros datos
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sistema_logueo.urls'

#Esto es directamente la parte que tenemos configurada para los servicios 

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sistema_logueo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

#ESTO ES SUMAMENTE IMPORTANTE, ES EL TIPO DE BASE DE DATOS A LA QUE ESTAMOS CONECTADOS

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3', #eSTO SE PUEDE CAMBIAR A OTRO TIPO DE BASE DE DATOS
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


#Configuraciones genericas 
# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/' #Esto es para vincular nuestros archivos de maquetado

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
